paths:
  dataset_images_dir: "D:/Dev/LAB_RESEARCH_PROJECT/NAFOSTED/UI/video_tracking_desktop/dataset/test"
  eval_results_dir: "D:/Dev/LAB_RESEARCH_PROJECT/NAFOSTED/yolo_tracker/eval_results"
  models_dir: "D:/Dev/LAB_RESEARCH_PROJECT/NAFOSTED/UI/video_tracking_desktop/models"

yolo:
  conf: 0.25         # Ngưỡng Confidence score phát hiện đối tượng (0.0 đến 1.0)
  iou: 0.45          # Ngưỡng NMS IoU loại bỏ bounding box trùng lặp
  imgsz: 640         # Kích thước ảnh suy luận YOLO (ví dụ: 640, 1084, 1280)
  tracker: "bytetrack.yaml" # Thuật toán tracking ("bytetrack.yaml" hoặc "botsort.yaml")
  verbose: false     # Tắt log in ra terminal từng frame
